khaeru/sdmx

.travis.yml
doc/sources.rst
doc/whatsnew.rst
sdmx/api.py
sdmx/reader/sdmxml.py
sdmx/source/wb_wdi.py
sdmx/sources.json
sdmx/tests/test_api.py
sdmx/tests/test_docs.py
sdmx/tests/test_source.py
sdmx/tests/test_sources.py
sdmx/writer/pandas.py

Closes #9.
Other changes:
- Update tests for changes in targeted web services.
- Use the official domain for the ECB service.
- Fix macOS CI, since the build environment has changed.
- Adjust imports to be compatible with pandas 1.1.0.

 Add World Bank WDI service

---

doc/whatsnew.rst
sdmx/message.py
sdmx/model.py
sdmx/reader/sdmxml.py
sdmx/tests/data/__init__.py
sdmx/tests/test_model.py
sdmx/tests/writer/test_writer_xml.py
sdmx/writer/xml.py

Enhance writer.xml to round-trip DataMessages

---

doc/sources.rst
doc/whatsnew.rst
sdmx/message.py
sdmx/reader/sdmxml.py
sdmx/sources.json
sdmx/tests/test_message.py
sdmx/tests/test_source.py
sdmx/tests/test_sources.py
sdmx/writer/xml.py

- Update sources.json, docs, tests, and What's new.
- UNICEF returns ReportingBegin and ReportingEnd header fields; add these to `message.Header`
- Use Python's built-in datetime objects for Header fields, read/write strings in XML.

Add UNICEF as a supported source

---

.github/workflows/pytest.yaml
sdmx/reader/sdmxml.py
sdmx/tests/test_model.py
sdmx/tests/writer/test_writer_xml.py
sdmx/writer/xml.py

- Python 3.9 is still excluded because pydantic 1.6.1 does not support it. samuelcolvin/pydantic#1844 is merged but not yet released.
- Remove some needless trailing commas that black 20.8b1 wanted to treat differently than previous version of black.

Adjust CI configuration for Python versions

---

doc/sources.rst
doc/whatsnew.rst
sdmx/sources.json
sdmx/tests/test_source.py
sdmx/tests/test_sources.py

Please find attached a pull request adding a new source: Statistics Estonia uses the same server as the OECD (SDMX 2.0 and JSON).
Cheers,
Bertrand

Add Statistics Estonia as a source in sdmx/sources.json.

---

doc/whatsnew.rst
sdmx/api.py

Closes #26.
Attempt to make requests using an HTTP proxy.

Prepare and pass kwargs, including proxies, to requests.Session.send()

---

doc/sources.rst
doc/whatsnew.rst
sdmx/sources.json
sdmx/tests/test_source.py
sdmx/tests/test_sources.py

@khaeru please find attached a new source for the National Bank of Belgium. As STAT_EE, it is based on the same server as the OECD, hence limited to SDMX 2.0 and SDMX-json.

Add a new source with tests and doc for NBB (National Bank of Belgium)

---

doc/sources.rst
doc/walkthrough.rst
doc/whatsnew.rst
sdmx/model.py
sdmx/reader/sdmxml.py
sdmx/sources.json
sdmx/tests/test_source.py
sdmx/tests/test_sources.py
sdmx/urn.py
sdmx/writer/pandas.py
sdmx/writer/xml.py

- Add The Pacific Community's (SPC) DotStat instance "Pacific Data Hub DotStat" (PDH.stat) to data sources
- Update sources.json, docs, tests, and What's new
- Add support for handling `common:TimeRange`
**PR checklist**

Add SPC PDH.stat to sources

---

.github/workflows/pytest.yaml
sdmx/tests/test_client.py
sdmx/tests/test_sources.py

- **ECB**: `test_client.test_read_url` was using an old URL (wrong domain, no HTTPS), causing a redirect loop.
- **INSEE**: remove XFAIL expecting 503 errors. This was the last source using this setting.
- **ISTAT**: update test of workflow “47_850” for a DSD has changed since that issue was originally filed/fixed.
- **LSD**: tolerate SSL certificates treated as not valid on GHA runners. The certificates _are_ treated as valid on my local machine 🤷🏽‍♂️ 
As well:
- Run source tests immediately on push to `master`.This:
- Allows quicker spotting of these issues versus waiting for the nightly tests.
- Causes the benchmark test coverage to be set at 97% vs. 94%, because the source-specific code is tested.

Address failures in test_sources

---

doc/install.rst
doc/whatsnew.rst
setup.cfg

Tests began to fail today (https://github.com/khaeru/sdmx/runs/1992616989?check_suite_focus=true) because pydantic 1.8 was released and picked up.
This version includes improvements that will allow to eliminate some or all of the workarounds in `sdmx.util`; however, it also introduces samuelcolvin/pydantic#2422, for which a workaround is not obvious. This PR temporarily sets a requirement for pydantic < 1.8, until that bug is addressed. A subsequent PR will remove & also adapt to the new version.
This will require a quick patch release, v2.2.1, so that other code installing `sdmx1` gets a compatible version of pydantic.

Temporarily exclude pydantic 1.8

---

sdmx/__init__.py

Variable sdmx.__version__ is initialised with
'pkg_resources.get_distribution' using the appropriate
Distribution Package name 'sdmx1'.

Fix sdmx.__version__ bug #68

---

doc/sources.rst
doc/whatsnew.rst
sdmx/client.py
sdmx/source/__init__.py
sdmx/source/bbk.py
sdmx/sources.json
sdmx/tests/test_source.py
sdmx/tests/test_sources.py
sdmx/tests/test_urn.py
sdmx/urn.py

NB pandaSDMX handles CD2030 through duplicating the UNICEF source, which isn't necessary. This PR adds documentation to explain how to access this data using the existing source.

Add 2 web services (BBK, BIS) and document CD2030

---

doc/whatsnew.rst
sdmx/tests/writer/test_writer_xml.py
sdmx/writer/xml.py

If an observation value is falsy (like 0.0) then the structure specific XML writer is skipping it. This PR explicitly checks for `None`, to allow the falsy observation values to make it into the output.

Support observation values which are falsy

---

.github/workflows/publish.yaml
.github/workflows/pytest.yaml
doc/whatsnew.rst
sdmx/tests/reader/test_reader_xml.py
sdmx/tests/test_util.py
sdmx/tests/writer/test_pandas.py
sdmx/writer/pandas.py
setup.cfg

- Minor change to the test suite, mainly to reactivate scheduled GHA runs.
- Enable/use default Python 3.10 for CI.

Adjust test_parse_elem

---

doc/whatsnew.rst
sdmx/util.py

This addresses CI failures seen since the release of pydantic 1.9.0 with messages like:
```
AttributeError: 'tuple' object has no attribute 'popitem'
```

Adjust DictLike._validate_entry for compat with pydantic 1.9.0

---

.gitignore
doc/conf.py
doc/whatsnew.rst
sdmx/tests/test_model.py
sdmx/util.py
setup.cfg

Ubuntu nightly CI tests began failing with the following, e.g. [here](https://github.com/khaeru/sdmx/runs/7800359607?check_suite_focus=true#step:12:32):
```
WARNING: 
>>>-------------------------------------------------------------------------
Warning in /home/runner/work/sdmx/sdmx/doc/howto/create.rst at block ending on line 141
Specify :okwarning: as an option in the ipython:: block to suppress this message
----------------------------------------------------------------------------
<ipython-input-15-2eb198031efc>:7: DeprecationWarning: `copy_on_model_validation` should be a string: 'deep', 'shallow' or 'none'
return Observation(
<<<-------------------------------------------------------------------------
Exception occurred:
File …
```

Update for pydantic 1.9.2

---

.gitignore
doc/whatsnew.rst
sdmx/format/__init__.py
sdmx/reader/xml.py
sdmx/testing/report.py
sdmx/tests/format/test_xml.py
sdmx/tests/writer/test_pandas.py

Fix two issues that were causing failures of nightly CI jobs:
- Add a MIME type sometimes returned by Eurostat.
- Ensure names and descriptions are not lost when parsing ItemSchemes from SDMX-ML.
Also:
- Ensure all retrieved objects are present in a StructureMessage by using the maintainer's ID in the dictionary key; e.g. "AGENCY_A:CL_FOO" and "AGENCY_B:CL_FOO" instead of one entry "CL_FOO" that happens to be the last one parsed.

Fix common test failures

---

.github/workflows/pytest.yaml

- styfle/cancel-workflow-action v0.7.0 → v0.10.0
- actions/cache v2 → v3 and ref pip cache location
- actions/checkout v2 → v3
- actions/setup-python v2 → v4
- codecov/codecov-actions v1 → v3
- crazy-mac/ghaction-github-pages v2 → v3

Update actions versions

---

doc/sources.rst
doc/whatsnew.rst
sdmx/source/ilo.py
sdmx/sources.json
sdmx/tests/test_sources.py

Fix ILO entry point url and default parameters

---

doc/whatsnew.rst
sdmx/reader/xml.py
sdmx/testing/__init__.py

This provides a narrowly-scoped workaround for #102.

Handle incorrect `CubeRegion`/`KeyValue` usage by IMF

---

.github/workflows/lint.yaml
.github/workflows/publish.yaml
.github/workflows/pytest.yaml
.gitignore
doc/api.rst
doc/example.rst
doc/sources.rst
doc/whatsnew.rst
pyproject.toml
sdmx/client.py
sdmx/exceptions.py
sdmx/reader/xml.py
sdmx/rest.py
sdmx/source/__init__.py
sdmx/source/estat.py
sdmx/source/wb_wdi.py
sdmx/sources.json
sdmx/testing/__init__.py
sdmx/testing/report.py
sdmx/tests/reader/test_reader_xml.py
sdmx/tests/test_client.py
sdmx/tests/test_docs.py
sdmx/tests/test_rest.py
sdmx/tests/test_source.py
sdmx/tests/test_sources.py
sdmx/tests/test_urn.py
sdmx/urn.py
sdmx/writer/pandas.py
setup.cfg

- Supersedes and incorporates #107 (thanks @zymon!)
- SDMX-ML:
- Handle text elements like `<com:AnnotationURL/>` that have no text, rather than being simply empty.
- Handle additional XML namespaces mapped on on `<mes:StructureSpecificData>` and similar, with a specimen and test.
- Add `sdmx.rest.URL` class for constructing REST API URLs.
- All endpoints are now tested for every supported data source, even if they are expected to fail; sources.json and the test suite records and reports the expected failures.

Update ESTAT API URL and other improvements

---

pyproject.toml
sdmx/model.py
sdmx/source/__init__.py
sdmx/tests/test_model.py
sdmx/util.py
setup.cfg

[Mypy 1.1.1 was released on 2023-03-07](https://pypi.org/project/mypy/#history). Although there is no changelog or itemized list of changes in the release (cf. python/mypy#13279), it appears changes in this version cause mypy to now find errors in `sdmx` and downstream code.
In particular, this occurs when code sets InternationalString attributes with values that are not precisely InternationalString—for example, `str`:
```
from sdmx.model import Code
c = Code(id="FOO", name="Foo")
```
This PR adjusts.
I explored more elaborate solutions per e.g. https://stackoverflow.com/a/75242020/2362198, but the current approach appeared simplest.

Adjust for mypy 1.1

---

sdmx/model/__init__.py

#120 incorrectly used `warn(…, stacklevel=-2)`, not `stacklevel=2`. This fix causes the warnings to display at the correct location in the calling code.

Fix SDMX 3.0 deprecation warnings

---

.github/pull_request_template.md
.github/workflows/pytest.yaml
doc/api/reader.rst
doc/whatsnew.rst
pyproject.toml
sdmx/__init__.py
sdmx/model/common.py
sdmx/reader/xml.py
sdmx/source/__init__.py
sdmx/testing/__init__.py
sdmx/tests/reader/test_reader_xml.py
sdmx/tests/test_sources.py
sdmx/writer/pandas.py

Closes #116.
Housekeeping:
- Support pandas 2.0.0.
- Remove usage of deprecated `pkg_resources`; use `importlib.{metadata,resources}`.
- Drop support for Python 3.7.

Handle multiple versions of StructureMessage objects

---

doc/sources.rst
doc/whatsnew.rst
sdmx/sources.json
sdmx/tests/test_docs.py

The ECB API documentation page at https://data.ecb.europa.eu/help/api/overview contains the text:
> Migrating SDW API queries to EDP API queries
>
> The SDW web services API will be repointed to the ECB Data Portal API as of the official go-live. User requests will be automatically redirected for at least a year from https://sdw-wrest.ecb.europa.eu/ to https://data-api.ecb.europa.eu/. API request syntax will remain unchanged, as data structures and codifications remain the same.
There's no reference to indicate _what_ the actual "official go-live [date]" is (EDIT: appears to be https://data.ecb.europa.eu/blog/blog-posts/ecb-data-portal-live-now) but one test that checks the exact URL of a response began to fail as of 2023-06-27.
This PR adjusts.

Update ECB source URL

---

doc/api.rst
doc/whatsnew.rst
sdmx/dictlike.py
sdmx/experimental.py
sdmx/message.py
sdmx/model/common.py
sdmx/model/v21.py
sdmx/testing/__init__.py
sdmx/tests/test_docs.py
sdmx/tests/test_util.py
sdmx/tests/util/test_item_structure.py
sdmx/util/__init__.py
sdmx/util/item_structure.py
sdmx/writer/pandas.py

Parse structure information in `Item.description`

---

.gitignore
doc/sources.rst
doc/whatsnew.rst
sdmx/client.py
sdmx/model/common.py
sdmx/source/__init__.py
sdmx/source/oecd.py
sdmx/source/oecd_json.py
sdmx/sources.json
sdmx/tests/test_client.py
sdmx/tests/test_source.py
sdmx/tests/test_sources.py

OECD has added a SDMX 2.1-compliant REST API providing SDMX-ML.
- Add support, tests.
- Rename the former SDMX-JSON 1.0 endpoint to `OECD_JSON`.

Update OECD with SDMX-ML support

---

.github/workflows/pytest.yaml
.pre-commit-config.yaml
doc/whatsnew.rst
pyproject.toml
sdmx/tests/__init__.py
sdmx/tests/test_session.py
sdmx/writer/pandas.py

Remove distutils, which is no longer available/installed by default in Python 3.12. This was causing failures of scheduled runs of the sources.yaml workflow.
Housekeeping:
- Explicitly note Python 3.12 is supported and tested.
- Update pre-commit configuration:
- Update ruff 0.0.287 → 0.1.2.
- Replace black with ruff-format --check.
- Update mypy 1.4.1 → 1.6.1.
- Force a daily refresh of the cached environment for mypy via pre-commit.
- ~Update documentation~ N/A

Update data source tests for Python 3.12

---

doc/whatsnew.rst
sdmx/reader/xml/v21.py
sdmx/tests/test_dataset_ss.py

#135 updated this line:
https://github.com/khaeru/sdmx/blob/c28f50af506db86da6a35b7df13d8739362eb0df/sdmx/reader/xml/v21.py#L683
…to refer to BaseDataStructureDefinition, the base class for {v21,v30}.DataStructureDefinition.
However, `Reader.get_single()` does not match on subclasses unless `subclass=True` is given explicitly. The method would thus always return None, resulting in a warning, also perhaps other failures to use the provided DSD wherever code refers to the `ss_without_dsd` variable.
This PR corrects, closing #146.
- ~Update documentation~ N/A, bugfix

Use supplied DSD for structure-specific messages

---

.github/workflows/pytest.yaml
doc/whatsnew.rst
pyproject.toml
sdmx/client.py
sdmx/format/__init__.py
sdmx/format/xml/common.py
sdmx/tests/format/test_format_xml.py
sdmx/tests/reader/test_reader_xml.py
sdmx/tests/test_dataset.py
sdmx/tests/test_dataset_ss.py
sdmx/tests/writer/test_pandas.py
sdmx/writer/pandas.py

Pandas 2.2.0 (release 2024-01-19) deprecated "M" as an offset prefix; see [the release notes](https://pandas.pydata.org/docs/whatsnew/v2.2.0.html#deprecate-aliases-m-q-y-etc-in-favour-of-me-qe-ye-etc-for-offsets). This however remains a valid frequency;
```python
PeriodDtype(freq="M")
```
…still works.
- Adjust _maybe_convert_datetime() to use the PeriodDtype public API instead of pandas internals to parse these frequency specifiers.
- Address other warnings that appeared with pandas 2.2.0.
Housekeeping:
- Address some TODOs from https://github.com/khaeru/sdmx/pull/154#pullrequestreview-1826871349 and https://github.com/khaeru/sdmx/pull/154#issuecomment-1895452744 to limit reliance on the GitHub API in the test suite, thus also limit flakiness.
- ~Update documentation~

Adjust _maybe_convert_datetime for pandas 2.2.x

---

doc/whatsnew.rst
sdmx/reader/xml/v21.py
sdmx/tests/reader/test_reader_xml_v21.py
sdmx/tests/writer/test_writer_xml.py
sdmx/writer/xml.py

- Attach <com:Name> to the Agency, not the Contact.
- Write URI and e-mail as element text, not an attribute named "text".
- ~Update documentation~ Bug fix

Fix read/write of common.Contact

---

.github/dependabot.yml
.github/workflows/publish.yaml
.github/workflows/pytest.yaml
.pre-commit-config.yaml
doc/example.rst
doc/sources.rst
doc/whatsnew.rst
sdmx/source/comp.py
sdmx/source/empl.py
sdmx/source/estat.py
sdmx/source/grow.py
sdmx/tests/test_docs.py
sdmx/tests/test_sources.py

Closes #162.
Note that this PR does **not** address this TODO:
https://github.com/khaeru/sdmx/blob/7a2de97237860eac894399fd8c4cba9e09180234/sdmx/client.py#L279-L283
…as a consequence, some of the code in .source.estat.handle_references_param() is duplicative of existing code in Client._handle_get_kwargs(). The Source class will get a more extensive rework soon, in which this duplication can probably be removed.

Handle quirks of ESTAT-operated sources COMP, EMPL, GROW

---

doc/whatsnew.rst
sdmx/client.py
sdmx/rest.py
sdmx/source/__init__.py
sdmx/testing/__init__.py
sdmx/tests/reader/test_reader_xml_v21.py

Add support for data availability queries (availableconstraint) defined by the [SDMX 2.1 standard](https://github.com/sdmx-twg/sdmx-rest/blob/v1.5.0/v2_1/ws/rest/docs/4_6_1_other_queries.md)

Add support for data availability queries

---

.github/workflows/pytest.yaml
.pre-commit-config.yaml
doc/example.rst
doc/walkthrough.rst
doc/whatsnew.rst
pyproject.toml
sdmx/experimental.py
sdmx/format/xml/v21.py
sdmx/format/xml/v30.py
sdmx/message.py
sdmx/model/common.py
sdmx/model/internationalstring.py
sdmx/model/v21.py
sdmx/reader/json.py
sdmx/reader/xml/v21.py
sdmx/reader/xml/v30.py
sdmx/rest/common.py
sdmx/rest/v21.py
sdmx/rest/v30.py
sdmx/tests/model/test_common.py
sdmx/tests/test_docs.py
sdmx/tests/test_experimental.py
sdmx/tests/test_performance.py
sdmx/tests/test_sources.py
sdmx/tests/writer/test_pandas.py
sdmx/util/item_structure.py
sdmx/writer/csv.py
sdmx/writer/pandas.py

- Close #169.
- Improve StructureMessage.get() to be more flexible when artefact IDs are duplicated.
- Bugfix: allow copy.deepcopy(ItemScheme()).
- Housekeeping: bump versions of mypy, ruff.

Update doc/example and associated tests

---

.github/workflows/pytest.yaml
.pre-commit-config.yaml
doc/api.rst
doc/api/model.rst
doc/api/writer.rst
doc/conf.py
doc/whatsnew.rst
sdmx/model/common.py
sdmx/model/version.py
sdmx/tests/model/test_version.py
sdmx/tests/test_docs.py
sdmx/tests/test_urn.py
sdmx/urn.py

These support easier and more regular handling of version and URN identifiers for SDMX objects.

Add `.model.version`, improve `.urn`

---

doc/whatsnew.rst
pyproject.toml
sdmx/dictlike.py
sdmx/format/xml/v21.py
sdmx/model/common.py
sdmx/model/v21.py
sdmx/model/v30.py
sdmx/reader/xml/common.py
sdmx/reader/xml/v21.py
sdmx/rest/common.py
sdmx/sources.json
sdmx/testing/__init__.py
sdmx/tests/model/test_common.py
sdmx/tests/test_docs.py
sdmx/tests/test_model.py
sdmx/tests/test_sources.py
sdmx/tests/writer/test_csv.py
sdmx/tests/writer/test_pandas.py
sdmx/tests/writer/test_writer_xml.py
sdmx/util/__init__.py
sdmx/writer/base.py
sdmx/writer/pandas.py
sdmx/writer/xml.py

Improve handling of Metadata{StructureDefinition,Set} in SDMX-ML 2.1

---

doc/whatsnew.rst
pyproject.toml
sdmx/client.py
sdmx/format/xml/common.py
sdmx/reader/json.py
sdmx/reader/xml/common.py
sdmx/reader/xml/v21.py
sdmx/testing/__init__.py
sdmx/tests/reader/test_reader_xml_v21.py
sdmx/writer/pandas.py

Closes #199.
- ~Update documentation~ N/A, bug fix

Fix XML namespace handling in read of structure-specific SDMX-ML

---

doc/api/model-v21-list.rst
doc/api/model-v30-list.rst
doc/api/reader.rst
doc/implementation.rst
doc/whatsnew.rst
pyproject.toml
sdmx/model/common.py
sdmx/model/v21.py
sdmx/model/v30.py
sdmx/reader/__init__.py
sdmx/reader/csv.py
sdmx/testing/__init__.py
sdmx/tests/reader/test_reader_csv.py
sdmx/tests/test_model.py
sdmx/tests/writer/test_csv.py
sdmx/tests/writer/test_pandas.py
sdmx/writer/pandas.py

Read SDMX-CSV 2.0.0

---

doc/whatsnew.rst
sdmx/model/common.py
sdmx/tests/model/test_common.py

@glatterf42 reports that [here](https://github.com/iiasa/message-ix-models/actions/runs/11480171837/job/31948029245?pr=242) downstream tests fail with sdmx 2.19.0, but not sdmx 2.18.0.
This happens when an IdentifiableArtefact is initialized with an empty string (`""`) as its ID. Previously, this value was preserved. As a consequence of changes in #198, empty string was replaced with `MissingID`. There was no test covering this case.
This PR adds the missing test and a fix.
- ~Update documentation~ N/A, bugfix

Preserve IdentifiableArtefact(id="")

---

doc/sources.rst
doc/whatsnew.rst
sdmx/model/common.py
sdmx/reader/xml/v21.py
sdmx/sources.json
sdmx/testing/__init__.py
sdmx/tests/reader/test_reader_xml_v21.py
sdmx/tests/test_sources.py

Handle reference to non-existent concept identity in SDMX-ML 2.1

---

doc/conf.py
doc/whatsnew.rst
sdmx/format/xml/__init__.py
sdmx/tests/writer/test_writer_xml.py
sdmx/writer/xml.py

Closes #210
- ~Update documentation~ N/A, bugfix

Write SDMX-ML elements in XSD schema order

---

doc/api/reader.rst
doc/whatsnew.rst
sdmx/__init__.py
sdmx/client.py
sdmx/reader/__init__.py
sdmx/reader/base.py
sdmx/reader/csv.py
sdmx/reader/json.py
sdmx/reader/xml/__init__.py
sdmx/reader/xml/common.py
sdmx/reader/xml/v21.py
sdmx/tests/model/test_v21.py
sdmx/tests/reader/test_base.py
sdmx/tests/reader/test_reader_csv.py
sdmx/tests/reader/test_reader_json.py
sdmx/tests/reader/test_reader_xml.py
sdmx/tests/reader/test_reader_xml_v21.py
sdmx/tests/test_client.py
sdmx/tests/test_reader.py

Additions in #201/v2.19.0 allowed to read SDMX-CSV from files or streams. This is strictly what is specified by the SDMX-CSV standard.This PR extends to allow converting SDMX-CSV-*like* content in a pandas data frame using the same core features.
This is **non-standard**: the SDMX standards don't say anything about in-memory representations, so a pd.DataFrame *per se* is not and can not be SDMX-CSV; only a file that conforms to the standard. However, pandas is widely used and we already have a [HOWTO for doing such conversion manually](https://sdmx1.readthedocs.io/en/latest/howto/create.html). This PR is one step towards making this process easier. 
Some internal changes:
- A new class `Converter` with a simple API of two methods.
- A new to-level to_sdmx() method that allows to invoke …

Convert pandas.DataFrame as if it were SDMX-CSV

---

.github/workflows/pytest.yaml
.github/workflows/sources.yaml
.pre-commit-config.yaml
doc/whatsnew.rst
sdmx/reader/xml/v21.py
sdmx/tests/reader/test_reader_xml_v21.py
sdmx/tests/test_sources.py

This was the culprit behind khaeru/dsss#20.
Housekeeping:
- Replace [actions/setup-python](https://github.com/actions/setup-python) with [astral-sh/setup-uv](https://github.com/astral-sh/setup-uv).
- ~Update documentation~ N/A, bugfix

Fix read of str:Categorisation > str:Target from SDMX-ML 2.1

---

.github/workflows/sources.yaml
sdmx/tests/test_sources.py

1. In the "pytest" workflow, `TestISTAT.test_gh_104()`: the query of https://esploradati.istat.it/SDMXWS/rest/data/22_289/.IT..1+2.TOTAL.99 is returning a 404 error with the text/plain content:
> Error while retrieving Mappings from "Mapping Store"! Cause:Dataflow 'urn:sdmx:org.sdmx.infomodel.datastructure.Dataflow=IT1:22_289(1.0)' doesn't contain a mapping set
Despite the response code, this appears to be more of a 500 Internal Server Error → **mark as Xfail**
2. In the "sources" CI workflow, the "collect" job was not correctly updated in #215 to use `uv run python …`.
- ~Update documentation~ N/A, CI changes only

Address CI failures

---

.pre-commit-config.yaml
.readthedocs.yml
doc/api.rst
doc/sources.rst
doc/whatsnew.rst
pyproject.toml
sdmx/__init__.py
sdmx/client.py
sdmx/format/xml/common.py
sdmx/reader/xml/common.py
sdmx/reader/xml/v21.py
sdmx/reader/xml/v30.py
sdmx/source/__init__.py
sdmx/sources.json
sdmx/testing/__init__.py
sdmx/testing/data.py
sdmx/tests/format/test_format_xml.py
sdmx/tests/reader/test_reader_xml_v21.py
sdmx/tests/test_source.py
sdmx/tests/test_sources.py
sdmx/tests/writer/test_pandas.py
sdmx/urn.py
sdmx/writer/pandas.py
sdmx/writer/xml.py

Miscellaneous improvements for 2025-W02

---

.github/workflows/publish.yaml
pyproject.toml

Drop use of reusable workflow from iiasa/actions. Reusable workflows are not supported by pypa/gh-action-pypi-publish, and it does not seem likely that support is coming.
- ~Update documentation~ N/A, CI changes only

Use `uv` in first-party "publish" CI workflow

---

doc/whatsnew.rst
sdmx/format/xml/common.py
sdmx/tests/writer/test_writer_xml.py
sdmx/writer/xml.py

Follows fix for #180 in #218. Without this, errors occur like:
```
File "/home/runner/work/dsss/dsss/.venv/lib/python3.13/site-packages/sdmx/writer/xml.py", line 485, in _cat
reference(obj.artefact, tag="str:Source", style="Ref"),
~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/work/dsss/dsss/.venv/lib/python3.13/site-packages/sdmx/writer/xml.py", line 74, in reference
attrib = dict(id=obj.id)
^^^^^^
AttributeError: 'dict' object has no attribute 'id'
```
Also:
- Add a test, since this was only picked up in [`dsss` CI runs](https://github.com/khaeru/dsss/actions/runs/12761441370/job/35568456113).
- Following on #217, do not actually `_extract_zipball()` if the destination directory already exists. This avoids collisions that occur sporadically on GitHub Actions …

Don't write invalid ref in <str:Categorisation>

---

.github/workflows/pytest.yaml
README.rst
doc/license.rst
doc/whatsnew.rst
pyproject.toml
sdmx/testing/__init__.py
sdmx/tests/format/test_format_xml.py

Release v2.21.1

---

.pre-commit-config.yaml
.readthedocs.yaml
README.rst
doc/example.rst
doc/whatsnew.rst
sdmx/client.py
sdmx/model/v30.py
sdmx/testing/__init__.py
sdmx/testing/data.py
sdmx/tests/model/test_v21.py
sdmx/tests/test_client.py
sdmx/tests/test_dataset.py
sdmx/tests/test_docs.py
sdmx/util/requests.py

Around 2025-10-09, data returned by the ECB data source changed, causing one test to fail. Compare [A](https://github.com/khaeru/sdmx/actions/runs/15515080699) versus [B](https://github.com/khaeru/sdmx/actions/runs/15527164513/job/43708946215#step:5:1987). Specifically, series keys returned by the query https://data-api.ecb.europa.eu/service/data/EXR?detail=serieskeysonly changed, such that the number of keys matching a particular filter increased from 24 to 30:
```
keys = ECB.preview_data("EXR", {"CURRENCY": "CAD+CHF+CNY"})
>       assert len(keys) == 24
E       assert 30 == 24
E        +  where 30 = len([<SeriesKey: FREQ=A, CURRENCY=CAD, CURRENCY_DENOM=EUR, EXR_TYPE=SP00, EXR_SUFFIX=A>, <SeriesKey: FREQ=Q, CURRENCY=CAD, CURRENCY_DENOM=EUR, EXR_TYPE=SP00, EXR_SUFFIX=A>, <SeriesKey: …
```

Adjust expectation for test_request_preview_data()

---

.gitignore
doc/whatsnew.rst
sdmx/sources.json
sdmx/tests/test_sources.py

TestILO.test_gh_96() is flaky, as the server often returns 503 Server Error, leading to failure of 1 or more jobs in the daily scheduled CI run. To avoid this, use a stored response via sdmx-test-data instead of making an actual/network query. The test no longer hinges on the exact performance of a 'live' server.
Also:
- Change the default base URL for the ILO source to use `https://` instead of `http://`.
- ~Update documentation~ N/A, test changes only.

Address flaky TestILO.test_gh_96()
