khaeru/sdmx

doc/conf.py, doc/whatsnew.rst, sdmx/reader/__init__.py, sdmx/reader/sdmxjson.py, sdmx/tests/test_sources.py
- Add an optional dsd= keyword argument to sdmxjson.Reader.read_message().
=> Test data endpoints in test_sources.py

sdmx/format/xml.py
Fixes failing source test of SGR / datastructure, e.g. [here](https://github.com/khaeru/sdmx/runs/992140998?check_suite_focus=true#step:8:356).
=> Add MeasureDimension to format.xml._CLS_TAG

sdmx/reader/sdmxml.py, sdmx/tests/reader/test_reader_xml.py, setup.cfg
=> Handle additional ISO 8601 date formats

doc/conf.py, doc/sources.rst, doc/whatsnew.rst, sdmx/model.py, sdmx/source/insee.py, sdmx/tests/conftest.py, sdmx/tests/test_model.py, sdmx/tests/test_sources.py
=> Set default provider="ALL" for INSEE structure requests

.gitignore, doc/howto.rst, doc/howto/create.rst, doc/index.rst, doc/whatsnew.rst, sdmx/model.py, sdmx/reader/__init__.py, sdmx/reader/sdmxml.py, sdmx/tests/writer/test_writer_xml.py, sdmx/writer/xml.py
=> Add a HOWTO on creating SDMX-ML messages from pure Python

doc/sources.rst, doc/whatsnew.rst, sdmx/api.py, sdmx/reader/sdmxml.py, sdmx/remote.py, sdmx/source/lsd.py, sdmx/sources.json, sdmx/tests/test_source.py, sdmx/tests/test_sources.py
@khaeru please find attached firsts commits to start working on Issue #29.
=> Add a new source for Statistics Lithuania; improve reader.sdmxml

doc/whatsnew.rst, sdmx/source/__init__.py
=> Respect override in add_source()

.github/workflows/pytest.yaml, doc/whatsnew.rst, sdmx/tests/writer/test_protobuf.py, sdmx/tests/writer/test_writer_xml.py, sdmx/util.py, sdmx/writer/xml.py, setup.cfg
=> Rearrange header elements to match XSD sequence

.github/workflows/pytest.yaml, doc/api.rst, doc/whatsnew.rst, sdmx/message.py, sdmx/model.py, sdmx/reader/xml.py, sdmx/tests/reader/test_reader_xml.py, sdmx/tests/test_message.py, sdmx/tests/test_model.py, sdmx/tests/writer/test_writer_xml.py, sdmx/util.py, sdmx/writer/base.py, sdmx/writer/pandas.py, sdmx/writer/xml.py
Developed for transportenergy/database#62.
=> Performance and other improvements

.github/workflows/lint.yaml, .github/workflows/publish.yaml, doc/dev.rst
Following the example of genno.
=> Add 'publish' CI workflow

doc/whatsnew.rst, sdmx/reader/xml.py, sdmx/tests/writer/test_writer_xml.py, sdmx/writer/xml.py
This is an attempt to fix #65. I've run this output through "SDMX Converter" and it reports that it is valid. Happy to make any changes as needed.
=> StructureSpecific support in XML writer

.github/workflows/pytest.yaml, doc/whatsnew.rst, sdmx/model.py, sdmx/tests/test_client.py, sdmx/tests/test_docs.py, sdmx/tests/test_model.py
=> Implement IdentifiableArtefact.__lt__

.gitignore, doc/walkthrough.rst, doc/whatsnew.rst, sdmx/client.py, sdmx/model.py, sdmx/tests/test_dsd.py, sdmx/tests/test_model.py
- Fix a bug noticed via transportenergy/database#62.
- Adjust doc/walkthrough.rst for changes in requests-cache 0.6.0.
This is the first update to requests-cache in about 1½ years.
=> Fix CubeRegion.__contains__

doc/whatsnew.rst, sdmx/reader/xml.py, sdmx/tests/test_sources.py
=> Handle <mes:Department>, <mes:Role>

.github/workflows/pytest.yaml, doc/whatsnew.rst, sdmx/client.py, sdmx/session.py, sdmx/testing.py, sdmx/tests/test_client.py
- Closes #75, #77.
- Addresses CI failures that appeared with the release of mypy 0.900, e.g. [here](https://github.com/khaeru/sdmx/runs/2780481493?check_suite_focus=true#step:12:15)
=> Minor bugfixes

.github/workflows/pytest.yaml, .gitignore, README.rst, doc/sources.rst, doc/whatsnew.rst, sdmx/testing/__init__.py, sdmx/testing/report.py
- ~Give the created artifact a name.~
The job takes about 12 minutes to run.
=> Separate tests of web services/endpoints

.github/workflows/lint.yaml, .github/workflows/publish.yaml, .github/workflows/pytest.yaml, doc/conf.py, doc/sources.rst, doc/whatsnew.rst, sdmx/format/xml.py, sdmx/message.py, sdmx/model.py, sdmx/reader/xml.py, sdmx/source/istat.py, sdmx/sources.json, sdmx/tests/test_sources.py
Partly addresses #104.
Also
- Add Metadata{flow,Structure}Definition classes per the Information Model.
=> Update ISTAT service URL

sdmx/model.py, sdmx/reader/xml.py, sdmx/tests/test_util.py
=> Adjust for mypy 0.990

doc/whatsnew.rst, pyproject.toml, sdmx/client.py, sdmx/reader/xml.py, sdmx/testing/__init__.py, sdmx/tests/reader/test_reader_xml.py, sdmx/tests/test_sources.py, setup.py
See discussion at https://github.com/khaeru/sdmx/issues/104#issuecomment-1305522794
=> Fallback to user-supplied DSD argument when reading XML

setup.cfg
Temporary mitigation for #112.
=> Temporarily require Sphinx <6

.github/workflows/pytest.yaml, doc/whatsnew.rst
=> Release v2.9.0

.github/workflows/sources.yaml, README.rst, doc/whatsnew.rst
Also:
- Add alt-text to README badges.
- ~Update documentation~
=> Release v2.10.0

doc/example.rst, doc/howto.rst, doc/howto/create.rst, doc/implementation.rst, doc/install.rst, doc/sources.rst, doc/walkthrough.rst, doc/whatsnew.rst, sdmx/model/common.py
- ~Update doc/whatsnew.rst~ N/A
=> Spell-check documentation

doc/whatsnew.rst
=> Release v2.12.0

doc/whatsnew.rst
=> Release v2.12.1

doc/whatsnew.rst
=> Release v2.13.1

README.rst, doc/api/model.rst, doc/api/reader.rst, doc/api/writer.rst, doc/conf.py, doc/dev.rst, doc/implementation.rst, doc/index.rst, doc/install.rst, doc/resources.rst, doc/sources.rst, doc/walkthrough.rst, doc/whatsnew.rst, sdmx/format/xml/common.py, sdmx/model/common.py, sdmx/rest/v30.py, sdmx/writer/csv.py
=> Release v2.14.0

doc/whatsnew.rst
=> Release v2.15.0

sdmx/format/xml/common.py
Following #154, GitHub Actions jobs—especially those running on macOS—sometimes fail with messages like:
```
E           RuntimeError: Failed to download SDMX-ML schema bundle
sdmx/format/xml/common.py:192: RuntimeError
------------------------------ Captured log setup ------------------------------
DEBUG    sdmx.format.xml.common:common.py:191 {'message': "API rate limit exceeded for 13.105.49.208. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}
```
This PR ~caches the downloaded bundle in the workflow to avoid these issues~ adjusts _extracted_zipball() to guess the zipball URL if the API query fails.
- ~Update …
=> Guess schema zipball URL if API query is rate-limited

doc/whatsnew.rst
=> Release v2.16.0

doc/whatsnew.rst
=> Release v2.17.0

doc/whatsnew.rst
=> Release v2.18.0

doc/whatsnew.rst
=> Release v2.19.0

doc/whatsnew.rst
=> Release v2.19.1

doc/api.rst, doc/conf.py, doc/sources.rst, pyproject.toml
- ~Update doc/whatsnew.rst~ N/A, formatting changes only
=> Change to furo Sphinx theme

doc/whatsnew.rst
=> Release v2.20.0

doc/whatsnew.rst
=> Release v2.21.0

.github/workflows/pytest.yaml, .github/workflows/sources.yaml
- ~Update documentation~ N/A; CI changes only.
=> Update nightly source tests

doc/example.rst, sdmx/tests/test_docs.py
Similar to #184.
- ~Update documentation~
=> Address CI failures in .tests.test_docs

pyproject.toml, sdmx/tests/format/test_xml.py
Closes #238.
- ~Update documentation~ N/A, tests/CI only.
=> Mark 3 tests as flaky

doc/whatsnew.rst
=> Release v2.23.1
